# Generated by Django 2.1 on 2019-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunjho_web_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectData_index', models.IntegerField()),
                ('subjectNo', models.TextField()),
                ('faculty', models.TextField()),
                ('subjectName', models.TextField()),
                ('teacher', models.TextField()),
                ('place', models.TextField()),
                ('units', models.TextField()),
                ('scoreData_index', models.IntegerField()),
                ('member', models.IntegerField()),
                ('A', models.FloatField()),
                ('B', models.FloatField()),
                ('C', models.FloatField()),
                ('D', models.FloatField()),
                ('F', models.FloatField()),
                ('other', models.IntegerField()),
                ('averageGPA', models.FloatField()),
                ('linkData_index', models.IntegerField()),
                ('link', models.TextField()),
            ],
        ),
    ]
