# Generated by Django 2.1 on 2019-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunjho_web_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allsubjectdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectno', models.TextField(blank=True, db_column='subjectNo', null=True)),
                ('faculty', models.TextField(blank=True, null=True)),
                ('subjectname', models.TextField(blank=True, db_column='subjectName', null=True)),
                ('teacher', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('units', models.TextField(blank=True, null=True)),
                ('member', models.IntegerField(blank=True, null=True)),
                ('a', models.FloatField(blank=True, db_column='A', null=True)),
                ('b', models.FloatField(blank=True, db_column='B', null=True)),
                ('c', models.FloatField(blank=True, db_column='C', null=True)),
                ('d', models.FloatField(blank=True, db_column='D', null=True)),
                ('f', models.FloatField(blank=True, db_column='F', null=True)),
                ('other', models.IntegerField(blank=True, null=True)),
                ('averagegpa', models.FloatField(blank=True, db_column='averageGPA', null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AllSubjectData',
                'managed': False,
            },
        ),
    ]
